# Numpy: Package for Multidimensional array
## Vector(1d)
### Matrix(2d or 1d)

### Create an array

In [1]:
import numpy as np

In [2]:
simple_list=[2,3]
np.array(simple_list)

array([2, 3])

In [3]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [4]:
list_of_lists=([1,2,3],[4,5,6],[7,8,9])
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [6]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(5,28)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27])

In [9]:
np.arange(5,35,6) #(lb,up,jump)

array([ 5, 11, 17, 23, 29])

In [10]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros(6,dtype=int)

array([0, 0, 0, 0, 0, 0])

In [12]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [14]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [15]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [16]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [17]:
np.linspace(0,10,15) #(lb,up,no of points req)

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [18]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [19]:
np.random.rand(2,4)


array([[0.2059477 , 0.46255368, 0.79311125, 0.93295377],
       [0.92949941, 0.5785013 , 0.2956883 , 0.49083748]])

In [20]:
np.random.randn(2,4)

array([[-0.20041297, -0.4283141 ,  0.09311893,  1.09481754],
       [-0.25935908, -0.94101685, -0.35132571, -1.10128581]])

In [21]:
np.random.rand(2,5)

array([[0.21901903, 0.76962863, 0.27695498, 0.13230133, 0.35265378],
       [0.80429635, 0.06599936, 0.80777873, 0.05906801, 0.96423017]])

In [22]:
np.random.randint(0,10,15)

array([4, 2, 4, 9, 7, 7, 2, 7, 6, 1, 8, 3, 9, 9, 2])

In [23]:
np.random.randint(10,100,15)

array([61, 24, 80, 23, 33, 98, 60, 10, 89, 18, 57, 22, 72, 19, 19])

In [24]:
np.random.randint(20,56,100)

array([29, 38, 29, 39, 44, 52, 38, 30, 44, 52, 50, 21, 48, 27, 41, 40, 30,
       43, 38, 23, 39, 36, 43, 34, 39, 37, 51, 38, 38, 36, 26, 27, 21, 29,
       22, 50, 28, 38, 44, 31, 20, 28, 50, 29, 33, 54, 46, 30, 24, 31, 31,
       43, 47, 27, 26, 22, 47, 49, 22, 40, 41, 54, 33, 36, 42, 55, 37, 41,
       26, 30, 46, 25, 49, 55, 24, 38, 46, 32, 45, 42, 50, 42, 21, 21, 30,
       35, 37, 51, 48, 25, 20, 52, 44, 40, 48, 46, 29, 49, 53, 33])

In [25]:
sample_array=np.arange(2,20)
sample_array

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [26]:
rand_array=np.random.randint(0,10,5)
rand_array

array([2, 5, 3, 5, 7])

In [29]:
sample_array.min()

2

In [30]:
sample_array.argmin()

0

In [31]:
rand_array.argmin()

0

In [32]:
rand_array.max()

7

In [33]:
rand_array.argmax()

4

In [34]:
sample_array.argmax()

17

In [35]:
sample_array.dtype

dtype('int32')

In [36]:
a=np.eye(5) #identity matrix
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [37]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
a=np.random.rand(2,3)
a

array([[0.35563413, 0.0015962 , 0.47007268],
       [0.04591942, 0.14236859, 0.43726021]])

In [39]:
a.T

array([[0.35563413, 0.04591942],
       [0.0015962 , 0.14236859],
       [0.47007268, 0.43726021]])

In [40]:
sample_array=np.arange(10,28)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27])

In [41]:
sample_array=sample_array.reshape(6,3)
sample_array

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

In [43]:
sample_array=sample_array.reshape(3,6)
sample_array

array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27]])

In [46]:
sample_array[2]=100
sample_array

array([[ 10,  11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20,  21],
       [100, 100, 100, 100, 100, 100]])

In [47]:
sample_array=np.arange(10,100)
sample_array


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [48]:
sample_array[1:12]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [49]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [50]:
sample_array[:]=1001
sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001])

### Two-Dimensional array

In [51]:
sample_matrix=np.array(([24,13,2,15],[15,2,54,65],[56,76,24,7]))
sample_matrix

array([[24, 13,  2, 15],
       [15,  2, 54, 65],
       [56, 76, 24,  7]])

In [52]:
sample_matrix[2][2]

24

In [53]:
sample_matrix[1][2]

54

In [54]:
sample_matrix[:,2]

array([ 2, 54, 24])

In [55]:
sample_matrix[1,1]

2

In [56]:
sample_matrix[1:3,2:4]

array([[54, 65],
       [24,  7]])

In [57]:
sample_matrix[1:,2:]

array([[54, 65],
       [24,  7]])

In [58]:
sample_matrix[2]

array([56, 76, 24,  7])

In [59]:
sample_array=np.arange(1,31)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [60]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60])

In [61]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08,
       1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10,
       7.20048993e+10, 1.95729609e+11, 5.32048241e+11, 1.44625706e+12,
       3.93133430e+12, 1.06864746e+13])

In [62]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
       4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
       5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558])

In [63]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
       3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582,
       3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738])

In [64]:
np.max(sample_array)

30

In [65]:
np.min(sample_array)

1

In [66]:
np.argmax(sample_array)

29

In [67]:
np.argmin(sample_array)

0

In [68]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676,
       729, 784, 841, 900])

In [69]:
np.std(sample_array)

8.65544144839919

In [70]:
np.var(sample_array)


74.91666666666667

In [71]:
np.mean(sample_array)

15.5

In [72]:
array=np.random.randn(3,4) ### normal distribution
array

array([[-1.09664611, -0.96955716, -0.52516308, -1.11805311],
       [-1.37349196, -0.83977499,  0.6866188 , -1.38025698],
       [-0.37517404, -0.82380627, -1.02707988, -1.67341565]])

In [73]:
np.round(array,decimals=3)

array([[-1.097, -0.97 , -0.525, -1.118],
       [-1.373, -0.84 ,  0.687, -1.38 ],
       [-0.375, -0.824, -1.027, -1.673]])

In [74]:
sports=np.array(['golf','cricket','fball','cricket','basketball'])
np.unique(sports)

array(['basketball', 'cricket', 'fball', 'golf'], dtype='<U10')

### Pandas

In [75]:
import pandas as pd

In [76]:
labels=['a','b','c','d']


In [77]:
list=[10,28,3,4]


In [78]:
import numpy as np

In [79]:
array=np.array([1,2,3,4])


In [80]:
dict={'w':10,'x':20,'y':30,'z':40}

In [81]:
pd.Series(list)


0    10
1    28
2     3
3     4
dtype: int64

In [82]:
pd.Series(list,index=labels)

a    10
b    28
c     3
d     4
dtype: int64

In [83]:
pd.Series(labels,list)

10    a
28    b
3     c
4     d
dtype: object

In [84]:
pd.Series(dict)

w    10
x    20
y    30
z    40
dtype: int64

### Pandas dataframe and indexing

In [85]:
sports1=pd.Series([1,2,3,4],index=['cricket','football','basketball','golf'])
sports1

cricket       1
football      2
basketball    3
golf          4
dtype: int64

In [86]:
sports1['basketball']


3

In [87]:
sports2=pd.Series([11,13,12,4],index=['cricket','football','baseball','golf'])
sports2

cricket     11
football    13
baseball    12
golf         4
dtype: int64

In [88]:
sports1+sports2

baseball       NaN
basketball     NaN
cricket       12.0
football      15.0
golf           8.0
dtype: float64

In [89]:

df1=pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H'.split(),columns='Score1 Score2 Score3 Score4 Score5'.split())
df1

Score1    Score2    Score3    Score4    Score5
A  0.898924  0.744281  0.784969  0.208483  0.659251
B  0.626527  0.215569  0.517356  0.750489  0.484984
C  0.809623  0.938244  0.407863  0.923770  0.392823
D  0.842255  0.824002  0.625183  0.653054  0.110185
E  0.780053  0.865127  0.259983  0.077746  0.296061
F  0.431774  0.067744  0.983232  0.247615  0.791312
G  0.252896  0.068667  0.637628  0.890701  0.349434
H  0.166810  0.667694  0.855231  0.494057  0.637139

In [90]:
df1['Score3']

A    0.784969
B    0.517356
C    0.407863
D    0.625183
E    0.259983
F    0.983232
G    0.637628
H    0.855231
Name: Score3, dtype: float64

In [91]:
df1[['Score2','Score1','Score5']]

Score2    Score1    Score5
A  0.744281  0.898924  0.659251
B  0.215569  0.626527  0.484984
C  0.938244  0.809623  0.392823
D  0.824002  0.842255  0.110185
E  0.865127  0.780053  0.296061
F  0.067744  0.431774  0.791312
G  0.068667  0.252896  0.349434
H  0.667694  0.166810  0.637139

In [92]:
df1['Score6']=df1['Score1']+df1['Score2']
df1


Score1    Score2    Score3    Score4    Score5    Score6
A  0.898924  0.744281  0.784969  0.208483  0.659251  1.643205
B  0.626527  0.215569  0.517356  0.750489  0.484984  0.842096
C  0.809623  0.938244  0.407863  0.923770  0.392823  1.747867
D  0.842255  0.824002  0.625183  0.653054  0.110185  1.666257
E  0.780053  0.865127  0.259983  0.077746  0.296061  1.645180
F  0.431774  0.067744  0.983232  0.247615  0.791312  0.499518
G  0.252896  0.068667  0.637628  0.890701  0.349434  0.321562
H  0.166810  0.667694  0.855231  0.494057  0.637139  0.834504

In [93]:
df1.drop('Score5',axis=1) 


Score1    Score2    Score3    Score4    Score6
A  0.898924  0.744281  0.784969  0.208483  1.643205
B  0.626527  0.215569  0.517356  0.750489  0.842096
C  0.809623  0.938244  0.407863  0.923770  1.747867
D  0.842255  0.824002  0.625183  0.653054  1.666257
E  0.780053  0.865127  0.259983  0.077746  1.645180
F  0.431774  0.067744  0.983232  0.247615  0.499518
G  0.252896  0.068667  0.637628  0.890701  0.321562
H  0.166810  0.667694  0.855231  0.494057  0.834504

In [94]:
df1.drop("E",axis=0)


Score1    Score2    Score3    Score4    Score5    Score6
A  0.898924  0.744281  0.784969  0.208483  0.659251  1.643205
B  0.626527  0.215569  0.517356  0.750489  0.484984  0.842096
C  0.809623  0.938244  0.407863  0.923770  0.392823  1.747867
D  0.842255  0.824002  0.625183  0.653054  0.110185  1.666257
F  0.431774  0.067744  0.983232  0.247615  0.791312  0.499518
G  0.252896  0.068667  0.637628  0.890701  0.349434  0.321562
H  0.166810  0.667694  0.855231  0.494057  0.637139  0.834504

In [95]:
df2={'ID':[101,102,103,107,176],'Name':['John','Mercy','Akash','Kavin','Lally'],'Profit':[20,54,56,87,123]}
df=pd.DataFrame(df2)
df

ID   Name  Profit
0  101   John      20
1  102  Mercy      54
2  103  Akash      56
3  107  Kavin      87
4  176  Lally     123

In [96]:
df.drop('ID',axis=1)

Name  Profit
0   John      20
1  Mercy      54
2  Akash      56
3  Kavin      87
4  Lally     123

In [97]:
df.drop(3)

ID   Name  Profit
0  101   John      20
1  102  Mercy      54
2  103  Akash      56
4  176  Lally     123

In [98]:
df['Name']

0     John
1    Mercy
2    Akash
3    Kavin
4    Lally
Name: Name, dtype: object

In [99]:
df[['Name','ID']]

Name   ID
0   John  101
1  Mercy  102
2  Akash  103
3  Kavin  107
4  Lally  176

In [100]:
### Assessment

1) Create a null vector of size 10
2) Create a null vector of size 10 but the fifth value should be one
3) Create a vector with values ranging from 10 to 65
4) Reverse the above vector
5) Create a 3x3 matrix with values ranging from 0 to 8


SyntaxError: unmatched ')' (4110177331.py, line 3)

In [101]:
#Assesment 1
import numpy as np
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [102]:
#Assesment 2
import numpy as np
x = np.zeros(10)
print(x)
print("Update fifth value to 1")
x[4] = 1
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update fifth value to 1
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [103]:
#Assesment 3
import numpy as np
v = np.arange(10,66)
print("Original vector:")
print(v)

Original vector:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65]


In [104]:
#Assesment 4
v[::-1]

array([65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

In [105]:
#Assesment 5
import numpy as np
x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
